### ISSUE TITLE
Develop a benchmark for simple aggregations over genotype data -- master issue

### ISSUE THREAD

**Issue by ebegoli** [ornl-oxford/genomics-benchmarks#2]
Perform an allele count over an array of genotype calls. If the genotype array is organised as in scikit-allel, with rows as variants and columns as samples, then this is an aggregation over the 
columns of the array, counting the number of 0s, 1s, 2s, etc., found in each row. 

In scikit-allel this is implemented in the _GenotypeArray.count_alleles()_ method. 

For datasets too large to hold in memory, the _GenotypeDaskArray.count_alleles()_ method performs the same computation but uses dask to parallelise over chunks of the underlying array. This is a useful computation for I/O benchmarking, because it is not computationally intensive so usually I/O bound, and also has to visit all data elements so gives an indication of overall throughput.  

Also as it can be parallelised via Dask it can be used to benchmark parallel I/O.   

Also it can be useful to get a sense of the speed of different compressors when using zarr to store the data - some compressors (e.g., LZ4) are faster than others (e.g., Zstd) but have a lower compression ratio (see genotype compressor benchmark for more details). A variation on this computation is to pass a value for the _subpop_ parameter, which restricts the computation to a subset of the columns of the array. This can be useful to check that accessing subsets of samples performs reasonably well, which in turn usually depends on tuning chunk size and shape in the underlying storage.

**Comment by alimanfoo** [comment]
Suggest to broaden this out to simple aggregations over genotype data, which includes allele count and other types of counting such as genotype counts, as illustrated in #15.
